name: Multi-Job Workflow

on: push

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "This is job 1"

  job-2:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "This is Job 2"