name: First Workflow

on: push

jobs: 
    hello-job:
        runs-on: ubuntu-latest

        steps: 
            - name: Step 1
              run: echo "Workflow starting"

            - name: Step 2
              run: pwd

            - name: Step 3
              run: ls

            - name: Step 4
              run: echo "Workflow Completed"